tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/cert.crt"
        keyFile: "/certs/cert.key"
  certificates:
    - certFile: "/certs/cert.crt"
      keyFile: "/certs/cert.key"
